### ISSUE TITLE
posts/index.html.erb 뷰를 나누기

### ISSUE THREAD

**Issue by shaynekang** [HwaYo/soma09#20]
[posts/index.html.erb](https://github.com/HwaYo/soma09/blob/51109370162e465b0b83dcb58f62eeca7a80489c/app/views/posts/index.html.erb)가 너무 길고 복잡한 것 같습니다.
[partial rendering](http://guides.rubyonrails.org/layouts_and_rendering.html#using-partials)으로 여러개로 나누면 좋을 것 같네요. ㅎㅎ

일단 생각나는 건
- [x] Post 생성 폼 나누기
- [x] Post 개별 정보 페이지 나누기
- [x] Comment 페이지 나누기
- [ ] Post(또는 Comment) 생성할 때 데이터 검증 실패하는 부분만 따로 나누기

정도겠네요.
더 추가할 게 있다면 추가해주세요. ㅎㅎ

**Comment by angdev** [comment]
4번째 부분은 #26 에서 하겠습니다.
