### ISSUE TITLE
Post 수정시 modal창 깨짐 현상 발생 

### ISSUE THREAD

**Issue by stompesi** [HwaYo/soma09#23]
"post를 한 3개 정도 쓰고 난뒤 가장 먼저쓴 글을 수정을 누를시 modal 깨짐현상" 발생합니다.

![2015-02-28 9 30 05](https://cloud.githubusercontent.com/assets/1393421/6423603/f8a01a08-bf2b-11e4-9889-7366d935867c.png)

**Comment by stompesi** [comment]
![2015-02-28 9 20 12](https://cloud.githubusercontent.com/assets/1393421/6423621/1c447454-bf2c-11e4-9e35-66db139e1341.png)

**Comment by shaynekang** [comment]
이건 우리가 쓰는 NEON 테마의 디폴트 버그(!?)입니다.(..)
본 프로젝트에서 일어날 확률이 매우 높은 버그이므로, 사전에 고쳐서 이용하면 좋을 것 같습니다. ㅋㅋ
