### ISSUE TITLE
사용자는 정사각형이 아닌 페이스북 프로필 사진을 올려도 사진이 일그러지지 않는다.

### ISSUE THREAD

**Issue by shaynekang** [HwaYo/soma09#8]
![screen shot 2015-01-25 at 4 13 09 pm](https://cloud.githubusercontent.com/assets/528040/5890732/28472f7e-a4ad-11e4-81e9-c6c1662ca32c.png)

사진 찌부됐음. ㅠㅠ 빨리 고쳐주셈~~!

**Comment by DevSusu** [comment]
https://developers.facebook.com/docs/graph-api/reference/v2.2/user/picture

css로 별짓 다해보고 있었는데 ㅠㅠ 어차피 정사각형 이미지만 쓸거면 url 저장할때 뒤에 들어가는 width, height옵션을 같이 저장하면 될듯 합니다..

```
http://graph.facebook.com/1597185260511748/picture?type=large&width=100&height=100
```

하면 100px \* 100px 짜리 이미지가 날라오는군요.

**Comment by DevSusu** [comment]
``` ruby
if Rails.env.production?
  config.omniauth :facebook, "711281738969472", "9972f7c88f47ab7731cabbe316f37a8c",
    image_size: 'square'
else
  config.omniauth :facebook, "405883329580558", "61b2b2b8ed6c24b1001bd5a670a194ef",
    image_size: 'square'
end
```

이렇게 해놓아도 되는군요 다만 해상도가 조금 낮게 나올 뿐.
(메인 페이지에서는 아무런 변화 없고 admin/user/ 페이지에서 볼때 좀 깨짐)

아니면

``` ruby
<%= image_tag(asset_url(asset_url(participant.user.image)+"&width=100&height=100"), class: "img-circle") %>
```

이라고 써도 됩니다. 앞의 방법이 전반적으로 적용되는 방법이라 더 선호될 것 같은데 어떻게 하는 것이 좋을까요?

**Comment by shaynekang** [comment]
음 선호하는 쪽으로 가시죠~ ㅎㅎ
