### ISSUE TITLE
사용자는 브라우저 너비에 꽉 채운 헤더를 볼 수 있다.

### ISSUE THREAD

**Issue by shaynekang** [HwaYo/soma09#9]
![screen shot 2015-01-25 at 4 15 12 pm](https://cloud.githubusercontent.com/assets/528040/5890745/7229338a-a4ad-11e4-958d-f7fec4476cdf.png)

우상단을 보시면 헤더에 빈 공간이 있습니다. ㅋ
빨리 고쳐주세요~~

**Comment by DevSusu** [comment]
이 현상을 어떻게 재현할 수 있을까요? 지금 제 컴퓨터 브라우저(Firefox, Chrom, Safari)는 모두 이상이 없는데 ㅠㅠ

**Comment by shaynekang** [comment]
음. 전 반대로 크롬, 파폭, 사파리 모두 발생하네요. ㅎㄷ

인스펙터로 살펴봤는데, 그리드(Grid)가 잘못된 것 같습니다.
부트스트랩 그리드 시스템은 하나의 row에 여러개의 col을 넣고, 칸을 가로로 정렬하고 싶으면 col를, 세로로 정렬하고 싶으면 row를 적용하는 구조입니다. ([링크 참조](http://getbootstrap.com/css/#grid))

지금 우리 서비스는
1. row가 두 개씩 중첩되어 있고 (`row` 안에 `row post-form` 과 `row post-list`가 있네요),
2. 포스트(Post)는 전부 세로정렬인데 `row post-list` 안에 전부 `col`로 들어가있고

해서 사이드이펙트로 네비게이션 바가 깨지는 것 같습니다. ㅎㅎ

제가 고칠려고 했는데 컴퓨터 세팅이 이상한건지 `bundle install`이 안 먹히네요. ㅠㅠ
다른 분들이 한 번 수정해보세요~
